name: Send Menu to Teams

on:
  #add cron
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  send-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyPDF2

      - name: Run Python Script and Capture Output
        id: run_script
        run: |
          python your_script.py | tee output.txt

      - name: Post Message to Teams
        if: success()
        run: |
          curl -H 'Content-Type: application/json' -d '{'text':'Hello from GitHub Actions!'}' ${{ secrets.TEAMS_WEBHOOK_URL }}
