name: Send Menu to Teams

on:
  schedule:
    - cron: "0 8 * * 1-5"
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  send-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pdfminer.six

      - name: Run Python Script and Capture Output
        id: run_script
        run: |
          # Run the Python script and save output to a temporary file
          python scripts/scrape_and_extract.py > menu_output.txt

      - name: Read Output from File
        id: read_output
        run: |
          # Read the content of the output file
          menu_output=$(<menu_output.txt)
          echo "menu_output<<EOF" >> $GITHUB_ENV
          echo "$menu_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post Message to Lönsklöbb
        if: success()
        run: |
          if [[ ! "${{ env.menu_output }}" =~ ^Failed ]]; then
            formatted_output=$(echo "${{ env.menu_output }}" | sed 's/$/  /; s/\n/\n/g')
            
            curl -X POST "${{ secrets.TEAMS_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
                "type": "message",
                "attachments": [
                  {
                    "contentType": "application/vnd.microsoft.card.adaptive",
                    "contentUrl": null,
                    "content": {
                      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                      "type": "AdaptiveCard",
                      "version": "1.2",
                      "body": [
                        {
                          "type": "TextBlock",
                          "text": "'"${formatted_output}"'",
                          "wrap": true
                        }
                      ]
                    }
                  }
                ]
              }'
          else
            echo "No notification sent as menu_output starts with 'failed'."
          fi
  

      - name: Post Message to 'Hvað er í matinn?'
        if: success()
        run: |
          formatted_output=$(echo "${{ env.menu_output }}" | sed 's/$/  /; s/\n/\n/g')
          
          curl -X POST "${{ secrets.TEAMS_WEBHOOK_URL_2 }}" \
          -H "Content-Type: application/json" \
          -d '{
              "type": "message",
              "attachments": [
                {
                  "contentType": "application/vnd.microsoft.card.adaptive",
                  "contentUrl": null,
                  "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.2",
                    "body": [
                      {
                        "type": "TextBlock",
                        "text": "'"${formatted_output}"'",
                        "wrap": true
                      }
                    ]
                  }
                }
              ]
            }'
